definitions:
  handlers.CreateResponse:
    properties:
      token:
        $ref: '#/definitions/models.Token'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.Health:
    properties:
      alive:
        type: boolean
    type: object
  handlers.HealthResponse:
    properties:
      Health:
        $ref: '#/definitions/handlers.Health'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.Ping:
    properties:
      id:
        type: string
      service:
        type: string
      time:
        type: string
    type: object
  handlers.PingResponse:
    properties:
      ping:
        $ref: '#/definitions/handlers.Ping'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.RefreshResponse:
    properties:
      token:
        $ref: '#/definitions/models.Token'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.RemoveResponse:
    properties:
      status:
        type: string
      v:
        description: API version
        type: string
    type: object
  handlers.ResponseData:
    properties:
      data:
        type: string
      status:
        type: integer
    type: object
  models.Token:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /_/health:
    get:
      consumes:
      - application/json
      operationId: get-service-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
            type: object
      summary: Show health service
  /_/ping:
    get:
      consumes:
      - application/json
      operationId: ping-service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
            type: object
      summary: Ping service
  /token.create:
    get:
      consumes:
      - application/json
      description: Generate new access_token and refresh_token
      operationId: create-token
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: user email
        in: query
        name: email
        type: string
      - description: user password
        in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.CreateResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Create new token
  /token.refresg:
    get:
      consumes:
      - application/json
      description: Generate new access_token and refresh_token
      operationId: refresh-token
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: refresh_token
        in: query
        name: refresh_token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RefreshResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Deactivate old token and create new
  /token.remove:
    get:
      consumes:
      - application/json
      description: Remove access_token or revome all tokens from this user
      operationId: remove-token
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: user access_token
        in: query
        name: access_token
        type: string
      - description: remove all tokens
        in: query
        name: all
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RemoveResponse'
            type: object
      summary: Remove token or all
